### ISSUE TITLE
[Feature] `Schematic`: исправить использование

### ISSUE THREAD

**Issue by Nelfimov** [atls/raijin#409]
### С чем связан запрос на фичу?

Необходимо восстановить использование плагина `schematic`.

### Расскажите как вы это себе видите

- [ ] восстановить работу плагина, протестировать
- [ ] обновить миграции на актуальные для нового бандла

**Comment by Nelfimov** [comment]
> * при сборке `schematics` ошибка типов в одном из сторонних пакетов:

Обновляй зависимости. Ставь `typecheckSkipLibCheck`. Патчь зависимость.

> * а вот это должно нормально работать?

Да

> у меня вот такая ошибка:
> 
> node:internal/modules/esm/get_format:218
>   throw new ERR_UNKNOWN_FILE_EXTENSION(ext, filepath);
>         ^
> 
> TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/operator/Documents/atls_raijin/yarn/cli/src/cli.ts
>     at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:218:9)
>     at defaultGetFormat (node:internal/modules/esm/get_format:244:36)
>     at defaultLoad (node:internal/modules/esm/load:122:22)
>     at async ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:479:32)
>     at async ModuleJob._link (node:internal/modules/esm/module_job:112:19) {
>   code: 'ERR_UNKNOWN_FILE_EXTENSION'
> }
> 
> Node.js v22.11.0

В корне проекта `source .env && export NODE_OPTIONS`

**Comment by kirill-ivanovvv** [comment]
@Nelfimov 

- не понимаю, как этот плагин должен триггериься. 
- доки направляют на использование `@angular/cli@latest` - `ng generate my-schematic-collection:my-schematic-name`
- а эта команда дает ошибку о том, что у нас не `angular-project` - `Error: This command is not available when running the Angular CLI outside a workspace.`

**Comment by Nelfimov** [comment]
Из твоего сообщения не понятно что ты делал/делаешь.

У плагина простая задача - приводить в порядок существующие проекты. Добавлять конфиги, удалять, править.

Работает в основном за счет миграций.

Сам плагин скорее всего старый, минимум полтора года он был "не у дел". Вероятно изменилось и API.

Пользуйся gpt

**Comment by kirill-ivanovvv** [comment]
> Из твоего сообщения не понятно что ты делал/делаешь.
> 
> У плагина простая задача - приводить в порядок существующие проекты. Добавлять конфиги, удалять, править.
> 
> Работает в основном за счет миграций.
> 
> Сам плагин скорее всего старый, минимум полтора года он был "не у дел". Вероятно изменилось и API.
> 
> Пользуйся gpt

- ключевой пакет не съедает esm-module
- посмотрел по исходнимкам, ключ типа `cjs` не обнаружил
- допишу ключ, чтобы при билде сохранялись файлы в формате cjs

![Image](https://github.com/user-attachments/assets/8abbecda-18f1-4779-99d9-365a6d465f03)

![Image](https://github.com/user-attachments/assets/2d83bde6-9ee5-47b5-9e84-da810809997c)

**Comment by Nelfimov** [comment]
1. пробуй через `createRequire` либо динамический импорт
2. с гпт общайся на русском - посмотри соседние чаты

**Comment by kirill-ivanovvv** [comment]
#### Что сделано:
- разбирался с schematic
- перебил `schematics` под `esm`
- бампнул, проверил `esm`
- патчи не помогли

#### Что дальше:
- gpt рекомендует переводить на cjs
- нужно подумат. по всей видимости действительно проще сделать сборку под cjs, потомучто esm походу не планируется - https://github.com/angular/angular-cli/issues/22786

#### Актуальная ветка:
- https://github.com/atls/raijin/tree/fix/schematic

**Comment by kirill-ivanovvv** [comment]
@Nelfimov нам же не критичен angular? переписываю на plop? https://plopjs.com/

**Comment by Nelfimov** [comment]
> [@Nelfimov](https://github.com/Nelfimov) нам же не критичен angular? переписываю на plop? https://plopjs.com/

А он подходит для наших задач? Генерация файлов - это одно. А вот работать с уже существующими? Он будет делать дубликат или определять изменения? В пример тебе `tsconfig.json` - мы изменили в `atls/raijin` его опции. Как с этим будет работать либа?

**Comment by kirill-ivanovvv** [comment]
> > [@Nelfimov](https://github.com/Nelfimov) нам же не критичен angular? переписываю на plop? https://plopjs.com/
> 
> А он подходит для наших задач? Генерация файлов - это одно. А вот работать с уже существующими? Он будет делать дубликат или определять изменения? В пример тебе `tsconfig.json` - мы изменили в `atls/raijin` его опции. Как с этим будет работать либа?

такаого функционала не нашел. в других либах тоже. 
тогда делаю сборку в cjs

**Comment by Nelfimov** [comment]
> тогда делаю сборку в cjs

Не делай. Зафиксируй, сделай соседнюю таску на правку линт и чек ошибок пока.

**Comment by kirill-ivanovvv** [comment]
#### Что сделано:
- код в `schematics` собирается в формате `esm`
- cli-инструменты angular работают в формате `cjs`, поэтому не могут прянть `esm-модули`
- при патче `angular-cli` сыпятся более глубокие ошибки, связанные с конфликтами модулей
- у аналогов сильно меньше функционала

#### Что дальше:
- на данный момент придумал тольлько один вариант - собрать пакет в формате cjs
- сборка typescript происходит по стандартному нашему конфигу
- можно добавить флаг в сборку, типа `--cjs или --module commonjs` для того, чтобы переписать необходимые параметры в конфиге при сборке

#### Актуальная ветка:
- https://github.com/atls/raijin/tree/fix/schematic

**Comment by kirill-ivanovvv** [comment]
@Nelfimov 
- вот такой есть проект - https://nx.dev/nx-api/node
- и генерация есть и миграции и вообще много функций

https://chatgpt.com/c/679a1516-6d50-8004-9ae0-90b903c18621

**Comment by Nelfimov** [comment]
Сделай кейс - обнови tsconfig в существующем проекте. Можно скринкастом - не могу найти время на эту траблу

**Comment by kirill-ivanovvv** [comment]
> Сделай кейс - обнови tsconfig в существующем проекте. Можно скринкастом - не могу найти время на эту траблу

правильно понял задачу:
- эта либа должна по заготовленному шаблону поменять tsconfig в руте?
- подготовить шаблон, отличающийся от текущего tsconfig (для теста)
- запустить через cli
- на выходе должна сохраниться миграция?

**Comment by Nelfimov** [comment]
> правильно понял задачу:
> 
> * эта либа должна по заготовленному шаблону поменять tsconfig в руте?
> * подготовить шаблон, отличающийся от текущего tsconfig (для теста)
> * запустить через cli
> * на выходе должна сохраниться миграция?

Да

**Comment by kirill-ivanovvv** [comment]
@Nelfimov 

- старый `schematics` выполняется через метод execute
- сравниваю с `lint-ом` - как понимаю у него 2 исполняющих метода. `executeRegular` и `executeProxy`
- правильно понимаю, что эти методы позволяют нам свой прогресс отрисовывать через компоненты? (вижу рендер jsx-компонентов)

**Comment by Nelfimov** [comment]
> - правильно понимаю, что эти методы позволяют нам свой прогресс отрисовывать через компоненты? (вижу рендер jsx-компонентов)

И да и нет. Оба позволяет отрисовывать в UI. Только один из них - обычное исполнение, а прокси - проверка контекста и енв, подключение pnp 

Твой случай покроется обычным execute

**Comment by kirill-ivanovvv** [comment]
#### Что сделано:
- разбирался с исходниками angular-schematics
- разбирался с текущим репозиторием, как в прошлый раз этот плагин был организован
- при запуске schematics через код столкнулся с аналогичной ошибкой - несостыковка модулей в файле `factory`
- еще раз пробовал пропатчить - возвращает ошибку без деталей - `FactoryCannotBeResolvedException [Error]: Schematic "project" cannot resolve the factory.`
- пробовал делать cjs-обертку (для esm) - аналогично
- запустил минимально работающий проект - сразу на cjs, без оберток - запустился из исходного кода, генерация прошла.

#### Что дальше:
- переберу файл `factory`
  - в уже работающий cjs-factory построчно перенесу фунцкии из необходимого нам esm-factory. с промежуточными проверками. может быть ошибка в коде factory

- есть вариант форкнуть репозиторий angular и переписать функции импортов на dynamic import
  - не до конца понимаю объем такой работы
- есть вариант добавить ключ для сборки в cjs, как предлагал изначально. чтото типа `yarn library build --type cjs`
- есть вариант уже собранный esm корвертировать в cjs? может быть при помощи esbuild, не углублялся в этот вариант, но, кажется, так можно.

#### Актуальная ветка:
- https://github.com/atls/raijin/tree/fix/schematic

**Comment by kirill-ivanovvv** [comment]
#### Что сделано:
- перебирал исходники, gpt
- запустил минимальный project generate - с одним файлом

#### Что дальше:
- рефактор
- свести с оригинальными конфигами для генерации проекта
- этот конфиг должен быть в формате cjs, при этом он импортирует наши пакеты, а они в esm
- сборка пакета schematics должна включать себя все импортируемые пакеты и конвертироваться в формат cjs

#### Актуальная ветка:
- https://github.com/atls/raijin/tree/fix/schematic

**Comment by Nelfimov** [comment]
@kirill-ivanovvv до завтра (включ.) давай попробуем доделать. Если не выходит - выпиливаем из бандла

**Comment by Nelfimov** [comment]
Что за format и кто его требует?

**Comment by kirill-ivanovvv** [comment]
> Что за format и кто его требует?

во всем проекте `format` упоминается только в `yarn-plugin-format`
но в новых пакетах он не используется

**Comment by Nelfimov** [comment]
Смотри тут: https://yarnpkg.com/cli/builder/build/bundle

Есть флаги для отключения минимизации и дебага.

**Comment by kirill-ivanovvv** [comment]
@Nelfimov 

- файл по этому пути запрашивает пакет `jsonc-parser`
- это вложенный пакет в `angular-devtools`
- я же правильно понимаю, что при сборке бандла - весь код, всех используемых пакетов включается в один файл. и соответвренно пути всех запрашиваемых файлов тоже включаются в один файл (например запрос функции по пути заменяется просто запросом функции, ведь они все в одном файле)


> [!IMPORTANT]  
> - по какому принципу yarn выбирает, какие пакеты добавить в код бандла
>   - предположение: yarn смотрит зависимости в свойстве `@yarnpkg/builder` и добавляет все + все вложенные (рекурсивно) в бандл. тоесть не сами зависимости, а уже их код.
>  - если так, то `jsonc-parser` должен гарантированно включиться и накаких запросов по этому пути не должно быть (код функции по этому пути должен быть включен в бандл, а использование импоритруемой функции должно быть заменено на использование функции, объявленной в бандле)
> - почему именно этот пакет не включается полностью?

```shell
Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: /home/operator/Projects/atls_raijin/yarn/cli/dist/impl/format
Not found: /home/operator/Projects/atls_raijin/yarn/cli/dist/impl/format
Not found: /home/operator/Projects/atls_raijin/yarn/cli/dist/impl/format.js
Not found: /home/operator/Projects/atls_raijin/yarn/cli/dist/impl/format.json
Not found: /home/operator/Projects/atls_raijin/yarn/cli/dist/impl/format.node
Not found: /home/operator/Projects/atls_raijin/yarn/cli/dist/impl/format.handlebars
Not found: /home/operator/Projects/atls_raijin/yarn/cli/dist/impl/format.hbs
```

**Comment by Nelfimov** [comment]
> * по какому принципу yarn выбирает, какие пакеты добавить в код бандла

Забирает все что видит. Однако могут быть библиотеки которые используют либо динамический импорт либо чтение через `readFile`. Такое надо патчить, см. примеры в репе.

**Comment by kirill-ivanovvv** [comment]
@Nelfimov 

- а както еще можно получить путь до пакета? - https://github.com/atls/raijin/blob/2274c9ffbf58d1b94f146b2cc1c2b57f376f7fb2/yarn/plugin-schematics/sources/getters/stream-report-callback.getter.ts#L33
- в raijin работает собранный бандл, в shdvor - нет:
- `@atls/schematics` добавил в рутовый package.json, зависимости подтянул

```console
➤ YN0001: Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@atls/schematics' imported from /home/operator/Projects/atls_shdvor/.yarn/releases/yarn.mjs
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:916:9)
    at moduleResolve (node:internal/modules/esm/resolve:973:20)
    at defaultResolve (node:internal/modules/esm/resolve:1206:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
    at ModuleLoader.resolveSync (node:internal/modules/esm/loader:386:17)
    at Object.resolve (node:internal/modules/esm/initialize_import_meta:27:25)
    at vmc (file:///home/operator/Projects/atls_shdvor/.yarn/releases/yarn.mjs:2334:1250)
    at file:///home/operator/Projects/atls_shdvor/.yarn/releases/yarn.mjs:2334:1340
    at tst.start (file:///home/operator/Projects/atls_shdvor/.yarn/releases/yarn.mjs:199:1970)
➤ YN0000: Failed with errors in 0s 27ms
```

**Comment by kirill-ivanovvv** [comment]
@Nelfimov мне даже не до пакета путь нужен, а до collection.json, соответственно он в пакете

**Comment by Nelfimov** [comment]
> [@Nelfimov](https://github.com/Nelfimov)
> 
> * а както еще можно получить путь до пакета? - 

Посмотри соседние плагины - там есть работа с проектами и воркспейсами. Так же json файлы это ассеты. Они, если не импортированы напрямую в js, не будут участвовать в бандле

**Comment by kirill-ivanovvv** [comment]
#### Что сделано:
- сборка в бандл

#### Что дальше:
- генерация в сборке работает только в raijin
- при тесте в shdvor такая ошибка:
- ошибка в поиске пути до пакета `@atls/scmatics`
```
[operator@archlinux atls_shdvor]$ yarn generate
Error: The "paths[0]" argument must be of type string. Received undefined
```

#### Актуальная ветка:
- https://github.com/atls/raijin/tree/fix/bundle-build

**Comment by TorinAsakura** [comment]
> #### Что сделано:
> 
> * сборка в бандл
> 
> #### Что дальше:
> 
> * генерация в сборке работает только в raijin
> * при тесте в shdvor такая ошибка:
> * ошибка в поиске пути до пакета `@atls/scmatics`
> 
> ```
> [operator@archlinux atls_shdvor]$ yarn generate
> Error: The "paths[0]" argument must be of type string. Received undefined
> ```
> 
> #### Актуальная ветка:
> 
> * https://github.com/atls/raijin/tree/fix/bundle-build

yarn generate - что? ты аргумент не передал

**Comment by kirill-ivanovvv** [comment]
> > #### Что сделано:
> > 
> > * сборка в бандл
> > 
> > #### Что дальше:
> > 
> > * генерация в сборке работает только в raijin
> > * при тесте в shdvor такая ошибка:
> > * ошибка в поиске пути до пакета `@atls/scmatics`
> > 
> > ```
> > [operator@archlinux atls_shdvor]$ yarn generate
> > Error: The "paths[0]" argument must be of type string. Received undefined
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### Актуальная ветка:
> > 
> > * https://github.com/atls/raijin/tree/fix/bundle-build
> 
> yarn generate - что? ты аргумент не передал

изменил команду. 
yarn generate -t/--type (project/library) - project дефолтный

**Comment by TorinAsakura** [comment]
Закрываю как выполненную базовую миграцию schematic: основной поток прошел через PR #488 (включая связанный #492). Оставшиеся узкие доработки ведем отдельными задачами (#586, #489).
